title: CV of Radomir
description:  My curriculum vitae
url: https://sonmirean.github.io/CV-jekyll/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
